Fixed #3023 for Graphs tab sub menu
Cacti/cacti pull request #3031
Opened 2019-10-14 14:50 UTC by ddb4github

2019-10-14 21:30 UTC, netniV requested changes
this needs a changelog entry

2019-10-15 03:21 UTC, ddb4github commented
will change changelog as soon with non-good grammar

2019-10-15 23:37 UTC, netniV commented on include/layout.js
> +	});
My understanding is that this will now trigger whenever a user clicks, as long as they are not in that menu.  Is that the intended purpose?

2019-10-16 01:53 UTC, ddb4github commented on include/layout.js
> +	});
Yes, line#2580 and line#2583 will be always called once user click.

2019-10-16 07:10 UTC, netniV approved these changes

2019-10-16 23:05 UTC, cigamit approved these changes

2019-10-16 23:05 UTC, merged