1.2.x
Cacti/cacti pull request #3322
Opened 2020-03-04 16:51 UTC by PVi1

fixed bug on login page and added support for nested groups searching in AD.

2020-03-04 21:41 UTC, netniV requested changes
Overall, looks promising.  However, I think this should really go into 1.3 as we should also be allowing people the option of whether to enable nested groups or not.  Currently, this would change functionality from the expected behaviour.

Also, we should have a CHANGELOG entry for the update.

2020-03-04 21:41 UTC, netniV commented on auth_login.php
> +                }
Spacing here needs to be sorted.  It should always be tabs before any wording, not spaces (see https://github.com/Cacti/documentation/blob/develop/Standards-Code-Formatting.md)

2020-03-04 21:41 UTC, netniV commented on lib/ldap.php
> +}
Again, spacing needs to be sorted out.

2020-03-04 21:41 UTC, netniV commented on lib/ldap.php
> +                        $query="(&(distinguishedName=$ldapUser)(memberOf:1.2.840.113556.1.4.1941:=$groupDN))";
Is this a Windows AD or an OpenLDAP specific query?  Does it apply to all LDAP systemm and if not, would this generate a warning?

2020-03-04 21:41 UTC, netniV commented on lib/ldap.php
> +                        return false;
could be simplified as:

```php
return (isset($ldapResults["count"]) && $ldapResults["count"] == 1);
```

Either way, the code should be checking the return values before continuing to the next call as you may have a `false` not an array, or search object.  I believe there is already a geterrordetails function that can help with that though without checking I'm not sure you can call it from there or not.

2020-03-08 16:52 UTC, cigamit commented
Okay, I've gone ahead and made the minor changes.  I'm going to merge, but the question of the general applicability of that search we should get an answer to.

2020-03-08 16:58 UTC, merged

2020-03-08 16:58 UTC, cigamit commented
I'm going to add the changelog separately.

2020-03-08 22:14 UTC, netniV commented
I still feel that this expands the scope of searches beyond what people may expect currently therefore allowing greater access from accounts that previously did not have them.