1.2.x
Cacti/cacti pull request #3667
Opened 2020-07-07 18:18 UTC by riversdev0

This code provides the following minor updates:
1. converts numbers to constants to represent static values
2. minor comment updates
3. additional debug output
4. improved code readability where the html table is generated

2020-07-07 18:53 UTC, riversdev0 commented on lib/spikekill.php
> -			case 'variance':
Reorder to match what you see in the Spikekill menu in the GUI

2020-07-07 18:54 UTC, riversdev0 commented on lib/spikekill.php
> -							$rra[$rra_num][$ds_num]['avgnksamples']       = 'N/A';
Redundant variables with a few lines above.

2020-07-07 18:54 UTC, riversdev0 commented on lib/spikekill.php
>  				$this->set_error("FATAL: You must specify either 'stddev', 'variance', 'float', or 'fill' as methods.");
Reorder to match what you see in the Spikekill menu in the GUI

2020-07-07 18:55 UTC, riversdev0 commented on lib/spikekill.php
> +								"</tr>\n\n",
Changed the location of the '<td>' tags so that the code is more readable.

2020-07-08 14:20 UTC, netniV commented on lib/spikekill.php
>  				$this->set_error("FATAL: You must specify either 'stddev', 'variance', 'float', or 'fill' as methods.");
Liking the use of constants.

2020-07-08 17:33 UTC, netniV requested changes
I thought we were going to target the spikekill changes against 1.3 for proper testing?

2020-07-08 17:46 UTC, riversdev0 commented
Two things:
1. This pull request doesn't fix any of the open issues with spikekill, it's mainly just a "getting organized" step before actually submitting a pull request for the real issues.
2. Since my understanding of GIT is limited, I've done some things that weren't wise, like requesting to merge my personal '1.2.x' branch into the Cacti `1.2.x' branch, without creating a separate personal branch first, which (i am now seeing) causes different things to get bundled together dynamically (rather than a point-in-time snapshot).  So, my apologies for the 'removespikes.php' changes which are unrelated and which i backed out.

2020-07-08 17:51 UTC, netniV approved these changes
OK, so I did another look over this and it appears to be mainly cursory changes relating to using constants and greater debugging.

2020-07-08 17:52 UTC, merged

2020-07-10 02:02 UTC, TheWitness commented
👍