Committing Linting and PHP Doc Updates
Cacti/cacti pull request #4018
Opened 2020-12-23 14:56 UTC by TheWitness

* This commit includes a number of changes around applying consistent code styling to Cacti using the great php-cs-fixer tool.
* It also includes the conversion of all of Cactis comments to proper PHP DocBlock formatted comments
* Note that a number of "template" comments have been put in place that will have to be updated to real comments.  This activity is a long way from being completely over.
* Note, as a part of this exercise, to overcome some ugly side affects of linting, several filter code blocks including HTML select objects needed to be modified.

Related to the DocBlock changes, there were several hundred documented functions in Cacti that first had to be moved from their existing documentation style to DocBlock, then once that was done, a greatly enhanced version of the PHP-Docblock-Generator was used to provide the coverage for the remaining functions without comment blocks.  The before and after are shown below for reference.

```
+-------------------------------------------------------------------------------------------------------------------------+
| PHP DocBlock Generator - Starting                                                                                       |
+-------------------------------------------------------------------------------------------------------------------------+
| Processing Starting - Settings below                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+
| Target Path: ../../src                                                                                                  |
| Recursion is: Enabled                                                                                                   |
| File Exclusions: vendor/, fa/                                                                                           |
| Included Functions: All Functions                                                                                       |
| Anonymous Functions: Skipped                                                                                            |
| PHPDoc Comment Style: Short                                                                                             |
+-------------------------------------------------------------------------------------------------------------------------+
| DocBlock Generation took 0.58 seconds.                                                                                  |
+-------------------------------------------------------------------------------------------------------------------------+
| There were 554 files total scanned and 225 files excluded.                                                              |
| There were 2058 functions found and 1320 were converted.                                                                |
| There were 8 classes found and 0 were converted.                                                                        |
| There were 1316 functions found with no comments.                                                                       |
| There were 744 existing docblock functions found.                                                                       |
| There were 0 existing non-docblock functions found.                                                                     |
| There were 0 read/write errors.                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------+
```

After:
```
+-------------------------------------------------------------------------------------------------------------------------+
| PHP DocBlock Generator - Starting - Dry Run Only                                                                        |
+-------------------------------------------------------------------------------------------------------------------------+
| Processing Starting - Settings below                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+
| Target Path: ../../src                                                                                                  |
| Recursion is: Enabled                                                                                                   |
| File Exclusions: vendor/, fa/                                                                                           |
| Included Functions: All Functions                                                                                       |
| Anonymous Functions: Skipped                                                                                            |
| PHPDoc Comment Style: Short                                                                                             |
+-------------------------------------------------------------------------------------------------------------------------+
| DocBlock Generation took 0.56 seconds.                                                                                  |
+-------------------------------------------------------------------------------------------------------------------------+
| There were 554 files total scanned and 225 files excluded.                                                              |
| There were 2058 functions found and 1 would be converted.                                                               |
| There were 8 classes found and 0 would be converted.                                                                    |
| There were 2 functions found with no comments.                                                                          |
| There were 2064 existing docblock functions found.                                                                      |
| There were 0 existing non-docblock functions found.                                                                     |
| There would be 0 read/write errors expected.                                                                            |
+-------------------------------------------------------------------------------------------------------------------------+
```

and for good measure, Cacti 1.2.x branch:

```
+-------------------------------------------------------------------------------------------------------------------------+
| PHP DocBlock Generator - Starting - Dry Run Only                                                                        |
+-------------------------------------------------------------------------------------------------------------------------+
| Processing Starting - Settings below                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------+
| Target Path: /var/www/html/cacti                                                                                        |
| Recursion is: Enabled                                                                                                   |
| File Exclusions: vendor/, fa/                                                                                           |
| Included Functions: All Functions                                                                                       |
| Anonymous Functions: Skipped                                                                                            |
| PHPDoc Comment Style: Short                                                                                             |
+-------------------------------------------------------------------------------------------------------------------------+
| DocBlock Generation took 0. [...]

2020-12-30 03:23 UTC, netniV requested changes
So, there are a bunch of things that need to be checked, verified or put into alignment.  Most of my comments are purely based on the differences here so there may be wider scoped changes.  I also only commented on the first couple of occurrences, not all of them, so there are more places that match the things I've highlighted.  Also, my comments may not be valid, just observations within the limited context.

2020-12-30 03:23 UTC, netniV commented on aggregate_graphs.php
>  		$save['id']                    = $aggregate_graph_id;
If the line space was missing, would this lint be ignored?

2020-12-30 03:23 UTC, netniV commented on aggregate_graphs.php
> +			}else {
Shouldn't there be a space before the else ?

2020-12-30 03:23 UTC, netniV commented on auth_login.php
> +	cacti_log("DEBUG: User '" . $username . "' attempting to login with realm ". $frv_realm . ', using method ' . $auth_method, false, 'AUTH', POLLER_VERBOSITY_DEBUG);
Since this is already using double quotes, why exit quotes to use the variable?

2020-12-30 03:23 UTC, netniV commented on auth_login.php
> +					cacti_log("DEBUG: User '" . $username . "' password is " . ($valid?'':'in') . 'valid', false, 'AUTH', POLLER_VERBOSITY_DEBUG);
Since this is already using double quotes, why exit quotes to use the variable?

2020-12-30 03:23 UTC, netniV commented on automation_devices.php
> +	if ($os != '-1' && in_array($os, $os_arr, true)) {
This seems to be a change but does it keep the functionality correct?

2020-12-30 03:23 UTC, netniV commented on automation_templates.php
> +		$headers                                = automation_get_child_branches($tree['id'], 0, $spaces, $headers);
If the index of the headers was in another variable, there woulnd't be such massive unnecessary indentation.... but that's at the cost of adding a temp variable.

2020-12-30 03:23 UTC, netniV commented on changelog.php
>  			}
If this was in braces, the above line wouldn't try to align with it.

2020-12-30 03:23 UTC, netniV commented on cli/audit_database.php
> +							if (array_search($dbc['table_field'], $col_added, true) === false) {
Will this additional parameter change the program effect?

2020-12-30 03:23 UTC, netniV commented on cli/poller_graphs_reapply_names.php
> -	if (!$debug) print ".";
Should really be in braces?

2020-12-30 03:23 UTC, netniV commented on cli/poller_reindex_hosts.php
> +		print ('DEBUG: ' . $message . "\n");
Brackets unnecessary? And if all in double quotes, no need for variable join

2020-12-30 03:23 UTC, netniV commented on cli/rrdresize.php
> +				if (!in_array($local_data_id, $dt_data_sources, true))	continue;
This should follow the braces pattern a few lines above.

2020-12-30 03:23 UTC, netniV commented on cli/rrdresize.php
> +					if (!in_array($i, $ds_superfluos_ids, true)) {
Does this change the functonality?

2020-12-30 03:23 UTC, netniV commented on cli/rrdresize.php
> +					if (!is_dir($tmp_backup_folder . $host_id)) mkdir($tmp_backup_folder . $host_id);
Should be in braces

2020-12-30 03:23 UTC, netniV commented on cli/rrdresize.php
> +			2 => array('file', '/dev/null', 'a')	// stderr
Indentation looks off

2020-12-30 03:23 UTC, netniV commented on cli/sqltable_to_php.php
> +	if (in_array($table, $tables, true)) {
Will this break functionality?

2020-12-30 03:23 UTC, netniV commented on cmd.php
> +		print ('DEBUG: ' . $message . "\n");
Wouldn't this be better all in double quotes?

2020-12-30 03:23 UTC, netniV commented on lib/api_automation.php
> +		if (array_search($column, $field_names, true) === false) {
Is this change going to affect anything?

2020-12-30 03:23 UTC, netniV commented on lib/api_tree.php
>   * @arg $tree_id - the tree id of an existing tree of 0 for new tree
Shouldn't these now be @param not @arg?

2020-12-30 03:23 UTC, netniV commented on lib/api_tree.php
> + * @param mixed $propagate_changes
These are repeated from @arg's, need to choose a style and be consistent

2020-12-30 03:23 UTC, netniV commented on lib/auth.php
>  	/* policy == deny AND matches = ALLOW */
Comments are now in the wrong location

2020-12-30 03:23 UTC, netniV commented on lib/auth.php
> +			if (array_search($user_auth_realm_filenames[$file], $user_auth_roles[$role_name], true) === false) {
Does the extra parameter change or fix something?

2020-12-30 03:23 UTC, netniV commented on lib/auth.php
> + * @param 0 $graph_template_id
Is the first parameter @param the type or default value ?

2020-12-30 03:23 UTC, netniV commented on lib/data_query.php
> +	if (mb_detect_encoding($value, mb_detect_order(), true) === false) {
What does this change affect?

2020-12-30 03:23 UTC, netniV commented on lib/database.php
> + * @param $retries - the number a time the server should attempt to connect before failing
No type info here?

2020-12-30 03:23 UTC, netniV commented on lib/html_utility.php
> +					$_REQUEST[$name] = base64_decode($_REQUEST[$name], true);
Does this change affect anything?

2020-12-30 03:23 UTC, netniV commented on lib/installer.php
> +			$output .= Installer::sectionCode(sprintf('mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql'));
No point being an sprintf, looks like a copy/paste issue?

2020-12-30 03:23 UTC, netniV commented on lib/snmpagent.php
> +	if (!in_array($severity, array(SNMPAGENT_EVENT_SEVERITY_LOW, SNMPAGENT_EVENT_SEVERITY_MEDIUM, SNMPAGENT_EVENT_SEVERITY_HIGH, SNMPAGENT_EVENT_SEVERITY_CRITICAL), true)) {
Should this array be predefined rather than on the fly constantly?

2020-12-30 12:03 UTC, TheWitness commented on automation_templates.php
> +		$headers                                = automation_get_child_branches($tree['id'], 0, $spaces, $headers);
Yea, I encountered this rule causing issues like this in several other cases.  In those cases, I've added a newline, which is a good practice anyway.  Looks like I missed this one.  As a remediation, I've discarded the $spaces variable as it was really a waste of a variable.

2020-12-30 12:05 UTC, TheWitness commented on aggregate_graphs.php
>  		$save['id']                    = $aggregate_graph_id;
If the newline was removed, the lint checker would fail and provide a diff showing all the added whitespace between the variable and the assignment.

2020-12-30 12:07 UTC, TheWitness commented on aggregate_graphs.php
>  		$save['id']                    = $aggregate_graph_id;
So, if you continue that thought to the commit flow, it would fail the check, but the author would know what to do in order to fix it.  I prefer adding whitespace in this case.  Some of our table column variables are long, but I guess it's for a reason.

2020-12-30 12:08 UTC, TheWitness commented on aggregate_graphs.php
> +			}else {
Yea, and there is a linting rule for this that I was unable to nail down in the first pass of the linting.  Some of the rules are counter-intuitive.

2020-12-30 12:09 UTC, TheWitness commented on aggregate_graphs.php
> +			}else {
I've got this corrected, and have added the '}else' artifact to something yet to be finished before we put this into production.  So, I'll mark this one resolved.

2020-12-30 12:12 UTC, TheWitness commented on auth_login.php
> +	cacti_log("DEBUG: User '" . $username . "' attempting to login with realm ". $frv_realm . ', using method ' . $auth_method, false, 'AUTH', POLLER_VERBOSITY_DEBUG);
Yea, agree.  I'll fix this one right now.

2020-12-30 12:17 UTC, TheWitness commented on auth_login.php
> +					cacti_log("DEBUG: User '" . $username . "' password is " . ($valid?'':'in') . 'valid', false, 'AUTH', POLLER_VERBOSITY_DEBUG);
There were several more like this in this one file alone.  I remediated them.  I'm sure this a broader issue, but does not affect code flow.  Marking this one resolved too.  I'll be doing a commit after I finish my full review of your comments.

2020-12-30 12:22 UTC, TheWitness commented on automation_devices.php
> +	if ($os != '-1' && in_array($os, $os_arr, true)) {
This is a good point.  In this case, both values are of type string, so there is no problem, I'll do a sweep of the code.  The third option check the type of the variable in addition to whether or not it matches if dynamically retyped, which is the legacy behavior.

2020-12-30 12:25 UTC, TheWitness commented on changelog.php
>  			}
Let me check this code.  We should require even the simplest if statements to be bracketed, but I could not find a rule for that.  Adding it to the list.

2020-12-30 12:26 UTC, TheWitness commented on cli/audit_database.php
> +							if (array_search($dbc['table_field'], $col_added, true) === false) {
No, as the types are string in all cases.

2020-12-30 12:29 UTC, TheWitness commented on cli/poller_graphs_reapply_names.php
> -	if (!$debug) print ".";
We had agreed very early on, that any if statement, regardless of how simple, would always be bracketed, though I have not found a specific linting rule for that presently.  It's on my list of open items.  Added bracketing and whitespace.  So, I'll mark this one resolved.

2020-12-30 12:32 UTC, TheWitness commented on cli/poller_reindex_hosts.php
> +		print ('DEBUG: ' . $message . "\n");
We should create a 1.3 mundane task anyway to move to PHP_EOL wherever we can.

2020-12-30 12:32 UTC, TheWitness commented on cli/rrdresize.php
> +				if (!in_array($local_data_id, $dt_data_sources, true))	continue;
Yup.

2020-12-30 12:35 UTC, TheWitness commented on cli/rrdresize.php
> +				if (!in_array($local_data_id, $dt_data_sources, true))	continue;
This code has to be Andi's.  It's not Reinhard's for sure.

2020-12-30 12:43 UTC, TheWitness commented on cli/rrdresize.php
> +					if (!in_array($i, $ds_superfluos_ids, true)) {
I'm going to say yes on this one, and make false.  Looking at the code, I don't even think that statement will ever match regardless of the existence of true, false.  I need to test this code, as I'm presently dubious of it's validity.

2020-12-30 12:46 UTC, TheWitness commented on cli/rrdresize.php
> +					if (!is_dir($tmp_backup_folder . $host_id)) mkdir($tmp_backup_folder . $host_id);
Agree.

2020-12-30 12:48 UTC, TheWitness commented on cli/rrdresize.php
> +			2 => array('file', '/dev/null', 'a')	// stderr
Yup, the linter does not catch these all for some reason, also using tabs prior to the eol for commenting.

2020-12-30 12:48 UTC, TheWitness commented on cli/sqltable_to_php.php
> +	if (in_array($table, $tables, true)) {
No.

2020-12-30 12:52 UTC, TheWitness commented on cmd.php
> +		print ('DEBUG: ' . $message . "\n");
I went ahead and made them all the same.

2020-12-30 12:52 UTC, TheWitness commented on lib/api_automation.php
> +		if (array_search($column, $field_names, true) === false) {
No, it should not as the columns are always strings.

2020-12-30 12:54 UTC, TheWitness commented on lib/api_tree.php
>   * @arg $tree_id - the tree id of an existing tree of 0 for new tree
Good catch, there are more too.  I thought I had caught them all, but getting 700 comments into PHP Doc is a boring and laborious task to get right no the first pass...

2020-12-30 13:04 UTC, TheWitness commented on lib/api_tree.php
> + * @param mixed $propagate_changes
PHP Doc specification is @param.  I did not enable the PHP Doc linting for the first phase of this project.  That'll come next, and it's changing with PHP supporting strong typing now too.  So, good thing we are employing autolinting in our workflows moving forward.

2020-12-30 13:07 UTC, TheWitness commented on lib/auth.php
>  	/* policy == deny AND matches = ALLOW */
We need to introduce a constant here to make it more readable.  So, not only agreeing with your comment, but stating that with the lack of a good constant, it's hard to read/believe.

2020-12-30 13:27 UTC, TheWitness commented on lib/auth.php
>  	/* policy == deny AND matches = ALLOW */
I've introduced the constant and rolled into the three files and corrected the comment blocks.

2020-12-30 13:28 UTC, TheWitness commented on lib/auth.php
> + * @param 0 $graph_template_id
We will resolve these issues in pass 2 of reconciliation.  I think maybe the linted did that for us in pass 1.

2020-12-30 13:35 UTC, TheWitness commented on lib/data_query.php
> +	if (mb_detect_encoding($value, mb_detect_order(), true) === false) {
Basically, the way that the linter rewrote this, and based upon our new database setup, it's essentially saying if the string value does not match any encoding type, primarily UTF-8, it will convert the value to a HEX string for the output.  I don't think we need to worry about this one, even for data queries with values in foreign languages.  This is actually handling it more precisely now.

2020-12-30 13:35 UTC, TheWitness commented on lib/data_query.php
> +	if (mb_detect_encoding($value, mb_detect_order(), true) === false) {
We can have more discussion on this if you like.

2020-12-30 13:35 UTC, TheWitness commented on lib/database.php
> + * @param $retries - the number a time the server should attempt to connect before failing
Yea, this is for phase 2.

2020-12-30 13:37 UTC, TheWitness commented on lib/html_utility.php
> +					$_REQUEST[$name] = base64_decode($_REQUEST[$name], true);
Yea, it's is written correctly.

2020-12-30 13:38 UTC, TheWitness commented on lib/installer.php
> +			$output .= Installer::sectionCode(sprintf('mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql'));
Funny how we do these reviews and it pop's up these little issues you create during late night coding sessions.  Got it fixed.

2020-12-30 13:42 UTC, TheWitness commented on lib/snmpagent.php
> +	if (!in_array($severity, array(SNMPAGENT_EVENT_SEVERITY_LOW, SNMPAGENT_EVENT_SEVERITY_MEDIUM, SNMPAGENT_EVENT_SEVERITY_HIGH, SNMPAGENT_EVENT_SEVERITY_CRITICAL), true)) {
He could have done this a bit differently, but I think the code is pretty harmless.  It does make for a long comparison though.  Let me fix that.  I don't want to do a global_arrays.php entry though as I don't think this is used more than in this one function.

2020-12-30 13:45 UTC, TheWitness commented on lib/auth.php
> +			if (array_search($user_auth_realm_filenames[$file], $user_auth_roles[$role_name], true) === false) {
No, both the array and the file are of type string.  So, should not affect anything.

2020-12-30 16:25 UTC, cigamit commented on lib/html_utility.php
> +					$_REQUEST[$name] = base64_decode($_REQUEST[$name], true);
Seems like a good safety check.  Returns false if its not a true base64 encoded string.

2020-12-30 19:25 UTC, TheWitness reviewed
I have reviewed all files and made the pattern changes requested by @netniV.  Going to withdraw @cigamit's review since he's quite busy at the moment.

2020-12-31 17:19 UTC, merged

2020-12-31 17:20 UTC, TheWitness commented
Okay, moving on to the moves.  Second pull request coming.