Only show sensitive graph information to Template Editors in the List View screen
Cacti/cacti pull request #4049
Opened 2021-01-11 20:14 UTC by datatecuk

The **List View** screen is showing sensitive information to users who only have access to view graphs.
![image](https://user-images.githubusercontent.com/5603694/104232289-0b5db080-5448-11eb-9b69-7d9c73888566.png)

This commit removes the **Device**, **Source Type** and **Source Name** columns to anyone who does not have the **Graph Templates** permission so the screen now looks like this to users who do not have the permission to edit templates.
![image](https://user-images.githubusercontent.com/5603694/104233308-94c1b280-5449-11eb-8b09-ac8bf7252b6f.png)

A new option in the user account has been added to show the User Community and Documentation links from the user menu.
![image](https://user-images.githubusercontent.com/5603694/104232739-ab1b3e80-5448-11eb-837c-0ce03c12fa02.png)

To show them navigate to **Configuration** > **Users**
Select the required user and click the **Permissions** Tab
Under the **Normal User** section you will see a **Show User Help Links** option enable this to see the User Community and Documentation links from the user menu.
![image](https://user-images.githubusercontent.com/5603694/104232924-eb7abc80-5448-11eb-8562-079286e3d337.png)

2021-01-11 23:05 UTC, TheWitness commented
First off, we are reversing the permission on the graph drill-downs.  So, the default will be to deny access, and then when you check the checkbox, the drill-downs will be permitted.  So, please preserve the 1.2.x code which has already made that change.

2021-01-11 23:24 UTC, datatecuk commented
We have, i am not sure why all of the other commits are showing in this pull request.
The 2nd from the bottom is the merge from the main 1.2.x being merged into my clone on here (b5b1bb6)
The bottom one is the actual changes that are being requested to merge from my fork into the main 1.2.x branch.

I have just done a pull from my fork and compared it to the main 1.2.x branch with WinMerge and the only difference is the changes in the last commit which are the **include\global_arrays.php**, **lib\functions.php** and **graph_view.php** files.

2021-01-11 23:32 UTC, datatecuk commented
Just removed the duplicate line from the **CHANGELOG** file so the only files that have changed from this commit are the **include\global_arrays.php**, **lib\functions.php** and **graph_view.php** files.

2021-01-11 23:41 UTC, datatecuk commented
Just realised that I still had the old text in the screen snip above which is what probably caused the confusion.

The screen actually looks like
![image](https://user-images.githubusercontent.com/5603694/104250759-2e975880-5466-11eb-80c0-661b96a4f269.png)

2021-01-13 20:50 UTC, netniV requested changes

2021-01-13 20:50 UTC, netniV commented on include/global_arrays.php
> +	28   => __('Show User Help Links')
I prefer to have a comma after the last item to prevent it showing up as a change the next time someone adds an entry 👍

2021-01-13 20:50 UTC, netniV commented on include/global_arrays.php
> +	__('Normal User')            => array(7, 19, 20, 22, 24, 25, 27, 28),
Not one for now, but I would like to see these be constants @TheWitness / @cigamit because how do you know what these are without looking up each one! maybe one we can cover during 1.3?

2021-01-13 20:50 UTC, netniV commented on lib/functions.php
> +		if (is_realm_allowed(28)) {
again, @cigamit / @TheWitness guess work is needed here until you look everything up.

2021-01-13 20:52 UTC, netniV requested changes

2021-01-13 20:52 UTC, netniV commented on graph_view.php
> +	}
Better to prime the array with shared items, and then only append the secured items within the if statement rather than duplicate code and risk something being missed during changes later.

2021-01-13 23:24 UTC, cigamit commented on include/global_arrays.php
> +	__('Normal User')            => array(7, 19, 20, 22, 24, 25, 27, 28),
Yes, agreed, we should use constants in 1.3

2021-01-13 23:29 UTC, cigamit commented on include/global_arrays.php
> +	28   => __('Show User Help Links')
I prefer the last item in an array to not have a comma, since some other languages (like JSON) error out with them.  Keeps me from repeating bad habits when I work on other things.

2021-01-15 01:29 UTC, TheWitness commented on include/global_arrays.php
> +	__('Normal User')            => array(7, 19, 20, 22, 24, 25, 27, 28),
Well, we should make that a 1.3 thing, down a little on the list as there is so much to be done.

2021-01-15 01:30 UTC, TheWitness commented on lib/functions.php
> +		if (is_realm_allowed(28)) {
Life is a long road, only once traveled by each of us.  One thing at a time.

2021-01-17 17:27 UTC, TheWitness commented
@datatecuk, all we are missing from my perspective is a CHANGELOG entry.  Do you have time to do this today?

2021-01-17 17:48 UTC, datatecuk commented
@TheWitness I have just pushed this for you now.

2021-01-17 17:52 UTC, TheWitness commented
Glad you did that.  Could you do one more thing?  Run the following script, and then add `cacti.pot` to the pull request

```bash
cd /var/www/html/cacti/locales
./build_gettext.sh
```

2021-01-17 18:18 UTC, TheWitness commented
@datatecuk, I hope you saw the lastest request.

2021-01-17 18:44 UTC, datatecuk commented
Is it just that single file you want as all files in the **/var/www/html/cacti/locales/LC_MESSAGES** and **/var/www/html/cacti/locales/po** have changed after running the **./build_gettext.sh** script.

2021-01-17 18:57 UTC, TheWitness commented
Just the single file.  Per our new documentation on pull requests, you should only include the `cacti.pot` in pull requests.  The rest of the language changes take place at https://translate.cacti.net.

2021-01-17 19:11 UTC, merged