Remove bogus early return from `nth_percentile_fetch_statistics`
Cacti/cacti pull request #4265
Opened 2021-05-17 01:09 UTC by KrisShannon

If there are more than one data source then the early return when a single
data source is missing data will cause all data sources to be ignored,  even
those that do have data.

Fixes #4263

2021-05-17 08:28 UTC, netniV requested changes
PLease can you add the CHANGELOG entry for the issue that this fixes.

2021-05-17 08:34 UTC, netniV commented
I've requested a review on this by @TheWitness as he changed it in #3340 as part of commit 621091f7a.  I think the fix seems OK, just want to be sure as I suspect this was added to speed things up.

2021-05-17 09:10 UTC, KrisShannon commented
Should this PR actually be against [1.2.x](https://github.com/Cacti/cacti/tree/1.2.x)?

It's a simple fix for a bug in the 1.2 branch.

2021-05-17 09:12 UTC, netniV commented
Technically, yes it should be since it's not a 1.3 specific fix.  Like I said the fix seems straight forward but just wondering if there was a logic behind it that I'm not seeing myself.

2021-05-18 08:50 UTC, KrisShannon commented
CHANGELOG entry added

2021-05-18 22:30 UTC, netniV approved these changes

2021-05-18 22:30 UTC, merged