Fixed: session fixation issue for PHP 5.4
Cacti/cacti pull request #4282
Opened 2021-05-25 12:17 UTC by ddb4github

Steps:
 1. access cacti/logout.php
 2. Open Firefox DevTools, modify cookie `Cacti` value to `randomsessionid`
 3. Input username/password, then click button `Login`
 4. Browser will forward to `cacti/index.php?csrf_timeout=true` with login UI
 5. Input username/password, then click button `Login` again
 6. Login success, and show `Console`
 7. Check cookie `Cacti` value, it's `randomsessionid`

Note:
 * Ubuntu 18 + PHP 7.2 has not this issue, and always regenerate session id to replace `randomsessionid`

2021-05-25 12:18 UTC, netniV requested changes
Please remember to update the change log and titles to plain English.

2021-05-25 13:30 UTC, TheWitness commented
Seems like it would need a version unfair and then shouldn't this have been upstreamed by somebody?

2021-05-25 13:33 UTC, TheWitness commented
RHEL7 does not go away before 2024, and not everyone does REMI.

2021-05-26 18:42 UTC, netniV approved these changes

2021-05-26 18:42 UTC, merged