Fixing #4284 - Parameters in array_key_exists (1.2.17 database upgrade)
Cacti/cacti pull request #4285
Opened 2021-05-29 06:54 UTC by mchorsley

Three parameters passed to array_key_exists function in 1_2_17.php.  Removed rogue third parameter.

2021-05-29 09:02 UTC, netniV requested changes
Thanks for the submission. We appreciate it. 

Fix itself looks good, but can you add a CHANGELOG entry with a matching title to the issue it's fixing?  

I would also suggest updating the title to be something more 'plain English' rather than tech speaking.

2021-06-03 03:53 UTC, netniV commented on CHANGELOG
> +-issue#4284: Database upgrade can fail - Uncaught argument count error
This should be up under 1.2.18 :)

2021-06-03 10:24 UTC, mchorsley commented on CHANGELOG
> +-issue#4284: Database upgrade can fail - Uncaught argument count error
OK, thanks. I'll make that change.

2021-06-03 10:47 UTC, mchorsley commented on CHANGELOG
> +-issue#4284: Database upgrade can fail - Uncaught argument count error
Pushed the change.  I originally added the log entry under 1.2.17 as it related to the 1_2_17.php upgrade file, but now realise that the PR (if approved) would be merged into 1.2.18.  Thanks for the guidance.

2021-06-05 20:38 UTC, merged

2021-06-05 20:38 UTC, netniV commented
It's all good.  Allowed me to fix up where I put a changelog item as mine was in the wrong place too :)