Update reorder_data_query.php
Cacti/cacti pull request #4306
Opened 2021-06-16 07:00 UTC by gadzet21

Indexing function for all data query id was missing.

2021-06-16 09:47 UTC, netniV commented
I like your idea on this, but not the implementation.  The setting of 'all' as a default value means it will automatically reindex all queries.  At the moment, the code will display the help syntax.

2021-06-16 09:51 UTC, netniV requested changes
Suggested changes. Also, when making a change like this, please add an entry to the CHANGELOG that corresponds to the issue tracker created for the pull request.

2021-06-16 09:51 UTC, netniV commented on cli/reorder_data_query.php
> +$query_id	= 'all';
This should NOT be the default value.  If both host_id and query_id are set to all, it will automatically reindex everything.  Set the default value to be blank, and then all setting all through the query id parameter.

2021-06-16 17:46 UTC, gadzet21 commented
I'm not sure if this was what the changes were supposed to look like - unfortunately I'm not github proficient yet.

2021-06-17 13:09 UTC, netniV approved these changes
Looks good.  We shouldn't really be applying features to 1.2.x, but I'll let this one slide.

2021-06-17 13:10 UTC, merged