Fixes error callbacks for php 8.0+ on 1.2.x
Cacti/cacti pull request #4383
Opened 2021-08-29 09:05 UTC by GregOriol

Following request on #4376 (https://github.com/Cacti/cacti/pull/4376#issuecomment-907680658), this PR fixes some php 8.0 issues with error callbacks on branch 1.2.x

2021-08-29 09:31 UTC, netniV requested changes
Hi, thanks for updating it to 1.2.x.  More and more people are likely to be using it under 1.2 so we will no doubt have other minor issues. 

When you rebased / repatched, you left out the changelog again so if you could get that updated with the originally bug tracker number (mot the PR) we will go ahead an commit it as the rest looks good. 

Thanks for the work 😃

2021-08-29 09:40 UTC, GregOriol commented
@netniV Do I create a "1.2.19" section in the changelog?

2021-08-29 09:45 UTC, netniV commented
You just type it in 😃 

However, that should already exist. You may need a pull and rebase pick it up

2021-08-29 09:50 UTC, GregOriol commented
Great! I think it should be good now :-)

2021-08-29 14:34 UTC, TheWitness commented
Great.  Thanks for the contribution!

2021-08-29 14:35 UTC, merged

2021-08-31 06:28 UTC, ddb4github commented
How about function `db_warning_handler` and `ErrorHandler`?

2021-08-31 07:21 UTC, GregOriol commented
@ddb4github You are right!

2021-08-31 12:19 UTC, netniV commented
We probably have a few plugins that need the same love too.