add addiitonal admin email notifications
Cacti/cacti pull request #4385
Opened 2021-08-29 18:40 UTC by bmfmancini

Add additional admin email alerts

2021-08-31 02:21 UTC, netniV requested changes

2021-08-31 02:21 UTC, netniV commented on cactid.php
> +                admin_email(__('Cacti System Warning'), __('WARNING: Cacti Daemon PID[' . getmypid() . '] Terminated on Device[' . gethostname() . ']', true, 'CACTID'));
You have used spaces instead of tabs.

2021-08-31 02:21 UTC, netniV commented on CHANGELOG
> +-feature#4385 Add additional admin email notifications
Missing colon :)

2021-08-31 02:21 UTC, netniV commented on poller.php
> +                admin_email(__('Cacti System Warning'), __('WARNING: Cacti Polling Cycle Exceeded Poller Interval by ' . ($loop_end-$loop_start-$poller_interval) . ' seconds', true, 'POLLER', $level)
You have used spaces instead of tabs.

2021-08-31 02:21 UTC, netniV commented on poller_automation.php
> +                admin_email(__('Cacti System Warning'), __('WARNING: Main Cacti database offline or in recovery'));
You have used spaces instead of tabs.

2021-08-31 02:21 UTC, netniV commented on poller_automation.php
> +#}
Is there a reason for this comment character ?

2021-08-31 02:21 UTC, netniV commented on poller_boost.php
> +                                admin_email(__('Cacti System Warning'), __('WARNING: Detected Poller Boost Overrun, Possible Boost Poller Crash', 'BOOST SVR'  ));
You have used spaces instead of tabs.

2021-09-01 19:50 UTC, bmfmancini commented
@netniV  all fixed

2021-09-01 23:54 UTC, merged