Use OS provided DejaVu font for RHEL/CentOS/SLES/Ubuntu
Cacti/cacti pull request #4594
Opened 2022-03-03 06:17 UTC by ddb4github

2022-03-04 14:22 UTC, TheWitness commented
@netniV, what do you think?  Does not consider Windows for sure.

2022-03-04 14:33 UTC, netniV requested changes
I think using the system supplied font is useful, though if it is behind our version of the font, this may cause issues.  However, since the packaged versions of cacti will remove fonts in favour of the system supplied ones, I think people like @paulgevers would cheer this change on.  It doesn't apply to windows currently, as we seem to hard code to the Arial font on windows, though we could use a font_paths array and a font_names array to combine them into a search path.

2022-03-04 14:33 UTC, netniV commented on lib/functions.php
> +			isset($database_sessions["$database_hostname:$database_port:$database_default"])) {
Tab should not replace the spaces if it's for alignment purposes.

2022-03-04 14:33 UTC, netniV commented on lib/functions.php
> +		}
Assumption of font path location.  This should really be an array so that it can be amended without affecting code flow.  Suggest using a foreach loop instead and break out if a valid font file is found.  If no font is fount, default to supplied font instead (which can be achieved by including that as a path in the array).

2022-03-04 14:33 UTC, netniV commented on lib/rrd.php
> +		}
Again see above.

2022-03-04 23:32 UTC, ddb4github commented on lib/functions.php
> +		}
Copilot auto output dozen of DejaVu paths, all of them do not match known RHEL/SLES/Ubuntu paths. I'm not sure which one for which OS. 
So I'll combine RHEL/SLES/Ubuntu path in array only.
```php
//Copilot completion
$dejavu_paths = array (
	'C:/Program Files/DejaVu/',
	'C:/Program Files (x86)/DejaVu/',
	'/usr/local/dejavu/',
	'/usr/local/openwin/local/share/dejavu/',
	'/usr/local/openwin/share/dejavu/',
	'/usr/local/share/dejavu/',
	'/usr/local/X11R6/local/share/dejavu/',
	'/usr/local/X11R6/share/dejavu/',
	'/usr/openwin/local/share/dejavu',
	'/usr/openwin/share/dejavu/',
	'/usr/share/dejavu/',
	'/usr/X11R6/local/share/dejavu/',
	'/usr/X11R6/share/dejavu/'
);
//RHEL/SLES/Ubuntu known path
$dejavu_paths = array (
	'/usr/share/fonts/dejavu/',
	'/usr/share/fonts/truetype/',
	'/usr/share/fonts/truetype/dejavu/'
);

2022-03-11 01:07 UTC, TheWitness commented
Let's make sure Windoz is covered.

2022-03-12 02:03 UTC, netniV commented
I would also like to keep the currently included font as backup.

2022-03-12 12:11 UTC, TheWitness commented
Jing, make the Cacti supplied Dejavu don't the last choice in the array.  Did you check that windows actually includes this font.  Maybe not by default.  I'll look after I'm fully alert.

2022-03-12 12:12 UTC, TheWitness commented
Okay, I must not be awake.  This is perfect now. 👍

2022-03-12 18:16 UTC, TheWitness commented
Everything looks right.  Thanks for your contribution Jing!

2022-03-12 18:16 UTC, merged