Add l messages
Cacti/cacti pull request #4741
Opened 2022-04-25 20:26 UTC by xmacan

2022-04-25 20:57 UTC, netniV requested changes

2022-04-25 20:57 UTC, netniV commented on lib/utility.php
> +	cacti_log('NOTE: Poller Cache repopulated by user ' . get_username($_SESSION['sess_user_id']), false, 'WEBUI');
Should check that this is not empty in case it's done by a Cli program

2022-04-25 20:57 UTC, netniV commented on utilities.php
> +	cacti_log('NOTE: Cacti DS Stats purget by user ' . get_username($_SESSION['sess_user_id']), false, 'WEBUI');
See above

2022-04-29 06:54 UTC, netniV commented
Still waiting on an update @xmacan ?

2022-04-29 07:00 UTC, xmacan commented on lib/utility.php
> +	cacti_log('NOTE: Poller Cache repopulated by user ' . get_username($_SESSION['sess_user_id']), false, 'WEBUI');
I overlooked your request. I'll fix it asap

2022-05-01 18:57 UTC, xmacan commented on lib/utility.php
> +	cacti_log('NOTE: Poller Cache repopulated by user ' . get_username($_SESSION['sess_user_id']), false, 'WEBUI');
Fixed .... but function repopulate_poller_cache is not executed from CLI ..

2022-05-01 18:58 UTC, xmacan commented on utilities.php
> +	cacti_log('NOTE: Cacti DS Stats purget by user ' . get_username($_SESSION['sess_user_id']), false, 'WEBUI');
see above :-)

2022-05-01 22:05 UTC, TheWitness commented
Actually the `install_cacti.php` may be calling it.

2022-05-01 22:06 UTC, TheWitness approved these changes

2022-05-02 00:40 UTC, netniV approved these changes

2022-05-02 00:40 UTC, merged