Domains based LDAP and AD Fullname and Email not auto-populated
Cacti/cacti pull request #4769
Opened 2022-05-11 13:22 UTC by dk-dksoft

Patch to resolve issue: https://github.com/Cacti/cacti/issues/4768

2022-05-12 13:49 UTC, TheWitness requested changes
Okay, here are my comments and there are definately changes require:

1. In auth_login.php on line 549, you mis-spelled the function name.
2. In the function domain_ldap_search_cn() there are a few errors. First, on line 663, you are not using tabs for indentation.  Looks like spaces at the beginning.
3. On that very same line, our PSR requires that all if/then/else be enclosed in curly braces, so "if (condition) { blah(); } else { blah(); }
4. Delete line 659.  There are PSR versions that require it, but not Cacti.
5. You have a few blank lines between 690 and 693 and I see more soft/hard tab issues.

I would not be surprised if you grabbed this function strait from Cacti's lib/ldap.php, and again, we break our own rules in the whole set of if blocks around that whole function.

I had fixed this in a project in the Winter of 2021, but we backed the whole thing out.  If you could make these changes, then we can merge.  Might not be till after the 1.2.21 release though.

2022-05-12 13:49 UTC, TheWitness commented on auth_login.php
> +							$ldap_cn_search_response = domain_ldappp_search_cn($username, array($cn_full_name,$cn_email),get_nfilter_request_var('realm')-1000);
I think you have a typo here.  Did you test this?

2022-05-14 23:40 UTC, TheWitness commented
@dk-dksoft, are you planning on fixing your commit?

2022-05-15 19:15 UTC, dk-dksoft commented
Hello,
Thanks for comments!  Yes, i will make changes in a few days!

вс, 15 мая 2022 г., 02:41 TheWitness ***@***.***>:

> @dk-dksoft <https://github.com/dk-dksoft>, are you planning on fixing
> your commit?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Cacti/cacti/pull/4769#issuecomment-1126827442>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALVNBQOHQU26OA5XAFTIL23VKA2Y5ANCNFSM5VU5PSOQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-17 08:19 UTC, dk-dksoft commented on auth_login.php
> +							$ldap_cn_search_response = domain_ldappp_search_cn($username, array($cn_full_name,$cn_email),get_nfilter_request_var('realm')-1000);
sorry for that , i have copied it from my working enviroment but changed name in web . Now All is ok .

2022-05-19 12:47 UTC, TheWitness commented
We just need a CHANGELOG entry now.  Thanks!

2022-06-11 02:17 UTC, merged

2022-06-11 02:17 UTC, TheWitness commented
Closes #4819 - Domains based LDAP and AD Fullname and Email not auto-populated