Spelling
Cacti/cacti pull request #4792
Opened 2022-06-01 13:46 UTC by jsoref

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/cacti/commit/cd9c2f169cb291fbe418f541e7ff77b904ee524a#commitcomment-75085653

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/cacti/commit/801b0f02d78abedd0d9d099312c332a118536df9

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

I will be annotating this PR, and I fully expect to be asked to drop certain files.

2022-06-01 14:05 UTC, jsoref reviewed
I'm checkpointing now, because I'm going to drop two items eagerly... more comments later.

2022-06-01 14:05 UTC, jsoref commented on CHANGELOG
> +-issue#3760: Devices showing blank after deleting and Poller sync
Some projects don't like fixing typos in their changelogs. Quite happy to drop changes to this/similar files or any particular files/paths/types, just let me know.

2022-06-01 14:05 UTC, jsoref commented on CHANGELOG
> +-feature: Update JavaScript library: js.storage.js, d3.js, jquery.js, jquery.tablednd.js, jquery.timepicker.js
Brand

2022-06-01 14:05 UTC, jsoref commented on CHANGELOG
> +-feature: And much more...
Happy to drop this change. Arguably this should probably be `much, much, more` which wouldn't trip on my tooling. I'm still experimenting w/ this feature (and would happily ignore it anyway).

2022-06-01 14:05 UTC, jsoref commented on README.md
> +[Cacti Official YouTube Channel](https://www.youtube.com/channel/UC6ROmUGuuLa9BdHWzvGSY1w)
Brand

2022-06-01 14:05 UTC, jsoref commented on aggregate_graphs.php
> +	if (!isset_request_var('template_propagation')) {
This is probably an api break, but it's tied to SQL below, so I'm going to drop.

I leave things like this in so that people can talk about them/think about them for whether they want a followup.

2022-06-01 14:05 UTC, jsoref commented on aggregate_graphs.php
> +	/* we will show the templated representation only when there is a template and propagation is enabled */
Here's a more typical example of a doubled word where I'm fairly confident that the doubling was errant.

2022-06-01 14:05 UTC, jsoref commented on aggregate_templates.php
> +			AND template_propagation='on'",
Sigh, it's SQL, so, yeah, this can't be done. I'll drop it. (If someone wants to make a schema change, that's beyond the scope of this PR.)

2022-06-01 14:05 UTC, jsoref commented on auth_changepassword.php
> +				password_confirm: $('#password_confirm').val(),
API?

2022-06-01 14:05 UTC, jsoref commented on auth_login.php
> +			$_SESSION['sess_user_langauge'] = read_user_setting('user_langauge');
Oops, This wasn't intended. (I try to make sure that things don't spill across, but sometimes they slip through)

2022-06-01 14:49 UTC, jsoref reviewed
Most corrections were suggested by Google Sheets, but I made quite a few extra changes, and all fault is mine.

I'm sorry about the extra iterations here... I'll make one more push to fix a few items I noted here.

2022-06-01 14:49 UTC, jsoref commented on cacti.sql
> +) ENGINE=InnoDB ROW_FORMAT=Dynamic COMMENT='Aggregate Graph Items';
Not sure what `Graph Graph` is doing here. It's hard to read.

I'm assuming that this is a schema which means that even if this change should be made a corresponding schema migration would be needed. I expect to drop the changes to this file. So they're just cal-outs.

2022-06-01 14:49 UTC, jsoref commented on cacti.sql
> +  COMMENT='Cacti Reporting Reports';
Brand?

2022-06-01 14:49 UTC, jsoref commented on cli/add_graphs.php
> +	print "    Valid --reindex-method values include\n";
notable

2022-06-01 14:49 UTC, jsoref commented on cli/add_site.php
> +	echoQuiet("    --latitude=[Latitude]       e.g. '51.5115172'\n");
I didn't fix up whitespace, but certainly can

2022-06-01 14:49 UTC, jsoref commented on cli/audit_database.php
> +		print "Failed to create 'table_columns'";
Error message didn't match code

2022-06-01 14:49 UTC, jsoref commented on data_input.php
> +	form_start('data_input.php?action=edit&id' . get_request_var('data_input_id'));
notable

2022-06-01 14:49 UTC, jsoref commented on data_source_profiles.php
> +			request = 'data_source_profiles.php?action=item_remove_confirm&id='+id[1]+'&profile_id='+id[0];
?

2022-06-01 14:49 UTC, jsoref commented on docs/audit_schema.sql
> +INSERT INTO `table_indexes` VALUES ('data_template_rrd',0,'duplicate_dsname_constraint',3,'data_template_id','A',123,NULL,NULL,'','BTREE','');
Probably problematic

2022-06-01 14:49 UTC, jsoref commented on graphs_items.php
> +	form_start('graphs_items.php', 'graph_edit');
I think these items are more descriptive than meaningful

2022-06-01 14:49 UTC, jsoref commented on host.php
> +				$('#row_ping_retries').hide();
notable

2022-06-01 14:49 UTC, jsoref commented on include/global_arrays.php
> +	'April'		=> __('April'),
??

2022-06-01 14:49 UTC, jsoref commented on include/global_languages.php
> +		'lv-LV' => array('language' => 'Latvian',             'direction' => 'ltr', 'country' => 'lv', 'filename' => 'latvian_latvia'),
notable

2022-06-01 14:49 UTC, jsoref commented on include/plugins.php
> +$plugins_integrated = array('snmpagent', 'clog', 'settings', 'boost', 'dsstats', 'watermark', 'ssl', 'ugroup', 'domains', 'jquerieskin', 'secpass', 'logrotate', 'realtime', 'rrdclean', 'nectar', 'agg
oops, i didn't mean to do this.

2022-06-01 14:49 UTC, jsoref commented on include/themes/midwinter/colors.css
> +    --border-color-highlight: hsl(var(--hue), 0%, 75%);
notable

2022-06-01 14:49 UTC, jsoref commented on install/install.css
> +.cactiInstallSqlLeft, .cactiInstallSqlRight{
notable

2022-06-01 14:49 UTC, jsoref commented on install/upgrades/0_8_7h.php
> +	db_install_add_key('data_template_rrd', 'unique index',  'duplicate_dsname_constraint', array('local_data_id', 'data_source_name', 'data_template_id'));
i meant to drop changes to these upgrades files

2022-06-01 14:49 UTC, jsoref commented on lib/html.php
> +	print "<a class='iconLink mrtg' href='#' role='link' id='graph_" . $local_graph_id . "_mrtg'><img class='drillDown' src='" . $config['url_path'] . "images/timeview.png' alt='' title='" . __esc('Time
notable

2022-06-01 14:49 UTC, jsoref commented on lib/html.php
> +		$rkills .= html_spikekill_menu_item($value,html_spikekill_setting('spikekill_number') == $key ? 'fa fa-check':'fa', 'skills', 'kills_' . $key);
I'm not at all certain about this

2022-06-01 14:49 UTC, jsoref commented on lib/installer.php
> +		$rrdver = read_config_option('install_rrdtool_version');
notable

2022-06-01 14:49 UTC, jsoref commented on lib/rrd.php
> +	/* if the user desires to hide RRDtools watermark, set it */
or `worker`??

2022-06-01 14:49 UTC, jsoref commented on poller_reports.php
> +/* fetch all enabled reports that have a start time in the past */
Not at all certain

2022-06-01 14:49 UTC, jsoref commented on resource/script_queries/host_cpu.xml
> +	<output_delimiter>!</output_delimiter>
it's possible this is some third party api

2022-06-01 14:49 UTC, jsoref commented on settings.php
> +								duration: 100
notable

2022-06-01 14:49 UTC, jsoref commented on tests/build/www-fpm.conf
>  ;  %d: time taken to serve the request
This is a third party file, happy to drop

2022-06-01 14:49 UTC, jsoref commented on user_admin.php
> +					password_confirm: $('#password_confirm').val(),
notable

2022-06-02 16:59 UTC, netniV commented on auth_changepassword.php
> +				password_confirm: $('#password_confirm').val(),
We would need to double check this, because it can have a related mis-match.  Also, I would advise running this against the 1.2.x branch because that's the active patch branch currently.  develop is for new developments that aren't even at beta stage yet.

2022-06-02 17:00 UTC, netniV commented on cacti.sql
> +) ENGINE=InnoDB ROW_FORMAT=Dynamic COMMENT='Aggregate Graph Items';
It's because Aggregate Graphs have Graph Items

2022-06-02 17:01 UTC, netniV commented on cacti.sql
> +  COMMENT='Cacti Reporting Reports';
Someone can't spell our own name ;-)

2022-06-02 17:01 UTC, netniV commented on cli/add_site.php
> +	echoQuiet("    --latitude=[Latitude]       e.g. '51.5115172'\n");
Whitespacing should be fixed here.

2022-06-02 17:05 UTC, netniV commented on resource/script_queries/host_cpu.xml
> +	<output_delimiter>!</output_delimiter>
Again, this seems to be correct in the 1.2.x branch, so this work may be best applied there first.

2022-06-02 17:08 UTC, netniV commented
Thamks for the work, much appreciated.  The best way forward I think is to apply this against the 1.2.x branch for now.  You may find that a bunch of these are already corrected, we haven't merged into develop recently so there is likely more issues on develop than 1.2.x (hopefully!)

2022-06-02 17:09 UTC, netniV commented
Also, for the CHANGELOG, if there is a change to an entry, the original issue likely has the same title problem and needs to be updated too.

2022-06-04 08:10 UTC, TheWitness commented
Yea, totally agree.

2022-06-06 22:40 UTC, jsoref commented
My _guess_ is that I can't edit issue titles in this repo w/o being a member or something, so, I imagine I'd drop or stash those changes.

2022-06-06 23:33 UTC, netniV commented
Well, we would be able to handle that, but a heads up in the PR will give whomever is merging would need to handle the issue tracker updtaes

2022-06-07 01:54 UTC, jsoref commented on CHANGELOG
> +-feature: Update JavaScript library: js.storage.js, d3.js, jquery.js, jquery.tablednd.js, jquery.timepicker.js
I've temporarily dropped the changelog things. I've kept them in a branch, but I think I'd rather get everything else merged first.

2022-06-07 02:06 UTC, jsoref commented on auth_changepassword.php
> +							<td class='nowrap'><input type='password' class='ui-state-default ui-corner-all' id='current' name='current_password' autocomplete='current-password' size='20' placeholder='********'></td>
notable

2022-06-07 02:06 UTC, jsoref commented on auth_changepassword.php
> +			$.post('auth_changepassword.php?action=checkpass', { password: $('#password').val(), password_confirm: $('#password_confirm').val(), __csrf_magic: csrfMagicToken } ).done(function(data) {
previously flagged API item...

2022-06-07 02:06 UTC, jsoref commented on auth_login.php
> +							<td colspan='2'>
Notable

2022-06-07 02:06 UTC, jsoref commented on aggregate_graphs.php
> +	if (!isset_request_var('template_propagation')) {
Sigh. I forgot I meant to drop this and not pull it back in. I'll drop it again.

2022-06-07 02:06 UTC, jsoref commented on data_queries.php
> +						$header = '&header=false';
notable

2022-06-07 02:06 UTC, jsoref commented on include/global_arrays.php
> +		'message' => __('Data Input Saved.  You must update the Data Templates referencing this Data Input Method before the Data Collectors will start using any new or modified Data Input Fields.'),
Is this doubling like Aggregate Graph Graph Items?

2022-06-07 02:06 UTC, jsoref commented on include/global_form.php
> +			'array' => array(1 => 'NOTIFICATIONS', 2 => 'INFORMS')
Notable?

2022-06-07 02:06 UTC, jsoref commented on include/layout.js
> +		this.input = $('<input class="ui-autocomplete-input ui-state-default ui-selectmenu-text" style="background:transparent;border:0px;margin-left:-22px;padding:0px 3px 0px 22px;" value="'+value+'">')
Notable

2022-06-07 02:06 UTC, jsoref commented on include/themes/midwinter/css/media/compact-landscape.css
> +    color: var(--text-color-navigation-highlight);
Notable (and again in the portrait file)

2022-06-07 02:06 UTC, jsoref commented on lib/data_query.php
> +						if (preg_match("/(.*?)" . preg_quote($script_queries['output_delimiter']) . "(.*)/", $element, $matches)) {
notable

2022-06-07 02:06 UTC, jsoref commented on lib/installer.php
> +	public function processStepCheckDependencies() {
API?

2022-06-07 02:15 UTC, jsoref commented on cli/add_site.php
> +	echoQuiet("    --latitude=[Latitude]       e.g. '51.5115172'\n");
This doesn't appear in 1.2.x, so, as I've switched the target, this fell away (as did a number of others). The old commits will live on, so they can be fairly easily recovered. Additionally it isn't terribly hard to reproduce the corrections (even the manual whitespace fix-ups aren't particularly painful, although they're a bit more time consuming).

2022-06-07 02:18 UTC, jsoref commented on cacti.sql
> +  UNIQUE KEY `duplicate_dsname_constraint` (`local_data_id`,`data_source_name`,`data_template_id`),
This was called out elsewhere. I should have dropped it as it's pretty schema-ish which means it would need a migration and shouldn't be included in this large PR...

2022-06-07 02:18 UTC, jsoref commented on graphs.php
> +				/* save aggregate graph - graph items */
Half a proposal. But happy to drop.

2022-06-08 11:08 UTC, TheWitness commented on auth_changepassword.php
> +							<td class='nowrap'><input type='password' class='ui-state-default ui-corner-all' id='current' name='current_password' autocomplete='current-password' size='20' placeholder='********'></td>
Agree.

2022-06-08 11:09 UTC, TheWitness commented on auth_changepassword.php
> +			$.post('auth_changepassword.php?action=checkpass', { password: $('#password').val(), password_confirm: $('#password_confirm').val(), __csrf_magic: csrfMagicToken } ).done(function(data) {
Yikes

2022-06-08 11:12 UTC, TheWitness commented on graphs.php
> +				/* save aggregate graph - graph items */
It's good.

2022-06-08 11:14 UTC, TheWitness commented on include/global_arrays.php
> +		'message' => __('Data Input Saved.  You must update the Data Templates referencing this Data Input Method before the Data Collectors will start using any new or modified Data Input Fields.'),
Yea, same case.  Hyphen would be good.

2022-06-08 11:26 UTC, TheWitness requested changes
This is amazing work.  Please make the few updates and it'll be acceptable. Thanks for your efforts.

2022-06-08 11:26 UTC, TheWitness commented on include/global_arrays.php
> +		'message' => __('Data Input Field Saved.  You must update the Data Templates referencing this Data Input Method before the Data Collectors will start using any new or modified Data Input Fields.'),
Same comment here as a I've.  Use hyphen.

2022-06-08 11:26 UTC, TheWitness commented on include/global_form.php
> +			60 => __('%d Repetitions', 60)
I can't spell.  Thanks for you hard work and bots!

2022-06-08 11:26 UTC, TheWitness commented on include/global_form.php
> +			'array' => array(1 => 'NOTIFICATIONS', 2 => 'INFORMS')
Likely not.  Have to grep for that string and follow it.  It might just be a drop-down value in which it will be safe.

2022-06-08 11:26 UTC, TheWitness commented on lib/data_query.php
> +						if (preg_match("/(.*?)" . preg_quote($script_queries['output_delimiter']) . "(.*)/", $element, $matches)) {
Ouch

2022-06-08 11:26 UTC, TheWitness commented on lib/installer.php
> +	public function processStepCheckDependencies() {
Have to see where it's used.

2022-06-17 15:47 UTC, TheWitness commented on aggregate_graphs.php
> +	if (!isset_request_var('template_propagation')) {
Upon further review, you are right, this one has a broader scope.  We have to rename the database column too.  So, if you could drop this one, it would be appreciated.

2022-06-17 16:34 UTC, jsoref commented on aggregate_graphs.php
> +	if (!isset_request_var('template_propagation')) {
Right, it's actually currently dropped (I should have clicked `Resolve`, but I think I kinda wanted to make sure you saw it before I resolved it, since it's really a todo).

Noting before I make a push to update one other item (which I think is the only one I have outstanding).

2022-06-17 16:38 UTC, jsoref commented
Oh, I see you're actually pulling things in, great. Let me know if you need something from me. Sorry for not being more responsive, this is a thing I do in spare time, and that comes and goes....

2022-06-17 16:47 UTC, TheWitness commented on aggregate_graphs.php
> +	if (!isset_request_var('template_propagation')) {
I'm punching in some of your changes, but can take a break.  You sill see a number of updates in the conversation thread.  If you are working on things, and ready to do a push, then I can stop.  Just was not sure if you were working on it, and I'm trying to get us ready for next release.  Just keep me posted.  Taking a bike ride now.

2022-06-17 16:54 UTC, TheWitness commented
> Oh, I see you're actually pulling things in, great. Let me know if you need something from me. Sorry for not being more responsive, this is a thing I do in spare time, and that comes and goes....

Keep doing what you are doing.  I wasn't sure if you were active.  Maybe I pulled the trigger without first looking.  There are so many changes, I'm happier just waiting for your next push.  The one thing we have to avoid, at least for this release, is renaming database columns.

2022-06-17 17:04 UTC, jsoref commented on resource/script_queries/host_cpu.xml
> +	<output_delimiter>!</output_delimiter>
This change has actually survived to the 1.2.x branch (it'll still be there when I force push shortly).

2022-06-17 17:14 UTC, jsoref commented
I can't tell if my push was helpful or harmful. If it was harmful, please feel free to force-push to undo https://github.com/Cacti/cacti/pull/4792#event-6830459733.

(I think I forgot the scale of this PR. And I do know that there are Schema and Changelog changes that are intentionally dropped...)

2022-06-17 17:47 UTC, TheWitness commented
In the code, we now have to check for both delimeter and delimiter.

2022-06-17 17:47 UTC, TheWitness commented
You are doing a great job!

2022-06-17 20:06 UTC, jsoref commented on resource/script_queries/host_cpu.xml
> +	<output_delimiter>!</output_delimiter>
Ok, so this change can be applied, because code has been adjusted to tolerate the new spelling: https://github.com/Cacti/cacti/commit/d838c23bc60991073bfab01b752f68c2aebc08f2

2022-06-17 23:53 UTC, TheWitness commented on lib/rrd.php
> +	/* if the user desires to hide RRDtools watermark, set it */
Watermark

2022-06-18 01:32 UTC, TheWitness commented
This looks right to go.  Can you confirm?

2022-06-19 02:51 UTC, jsoref commented
Yep, :shipit:

2022-06-19 09:06 UTC, TheWitness commented
Very cool.  Thanks for your hard work!

2022-06-19 09:10 UTC, TheWitness approved these changes

2022-06-19 12:52 UTC, TheWitness commented
Will commit and then address these failures.

2022-06-19 12:52 UTC, merged