More Changes to #4287 - Help
Cacti/cacti pull request #4845
Opened 2022-06-25 00:05 UTC by TheWitness

This change does a few things:

- Make a new setting to force either local or use docs.cacti.net
- Move response to JSON so we can create messages in HTML
- More selective messages depending on the error
- Updates language files again

2022-06-25 00:12 UTC, TheWitness commented
Example not found on Web Site message:

![image](https://user-images.githubusercontent.com/1439914/175750329-996b46c2-a13e-4bff-877e-3376023b9324.png)

2022-06-25 00:14 UTC, TheWitness commented
Unable to reach site message:

![image](https://user-images.githubusercontent.com/1439914/175750396-3d560e93-0765-4179-a423-3637efede325.png)

2022-06-25 00:15 UTC, TheWitness commented
New setting

![image](https://user-images.githubusercontent.com/1439914/175750461-3cdd0864-4659-4789-92f5-ee45ba5543d8.png)

2022-06-25 00:17 UTC, TheWitness commented
Local install and file missing.

![image](https://user-images.githubusercontent.com/1439914/175750507-e381f8c4-b3d6-40e3-bc2f-c3e481fb04ef.png)

2022-06-26 07:48 UTC, netniV requested changes
The idea looks good in principle, but the more I think on it, the more it should really just be on the client-side.  

Consider this instead.  Creating a structure of possible URLs which is returned via the json call.  That list can vary dependant on the settings (like the one you've created).  These are then checked client side for validity in the order given.  If all fail, then we show a message when using multiple sources such as:

> The help page '%s' count not be reached on the Official Cacti Documentation website. or on the local server. Help can be found at %s.

Or alternatively, when the forced local setting is on:

> System settings prevent checking with official Cacti Group website, and Help page '%s' was not found locally. Help can be found at %s

Where the first parameter is the page and the second is the URL to it.  I am wondering if help pages should have their own array so we can use constants in the source.

2022-06-26 07:48 UTC, netniV commented on help.php
> +			)
This should be used for local servers, not for our server.  If our server cert is not valid, something dodgy is going on.

2022-06-26 07:48 UTC, netniV commented on help.php
> +			if ($contents != '' && !preg_match('/does not appear to exist/i', $contents)) {
When this is returned, do we not also st 404 as the status code?  Using a hard-coded string could cause help to fail between versions if that changes or a different language is usd.

2022-06-26 07:48 UTC, netniV commented on help.php
> +			} elseif ($contents != '' && preg_match('/does not appear to exist/i', $contents)) {
Hard coding, see above.

2022-06-26 07:48 UTC, netniV commented on help.php
> +						'message' => __('The Document page \'%s\' count not be reached.  The Cacti Documentation site is not reachable.  Consider downloading an official release to obtain the latest page help document
Wording is a little muddle, I feel (personally).  Consider:

> The Document page \'%s\' count not be reached on the Official Cacti Documentation website.

I feel this change removes the need for separate sentences (condensing) and more affirmation that we are trying to reach our own website.  But that's my personal opinion so may unnecessary.

2022-06-26 07:48 UTC, netniV commented on help.php
> +					'message' => __('The Document page \'%s\' count not be reached locally.  If you have installed from GitHub directly, consider downloading the distribution release and extracting the \'docs\' fol
I feel like we should have a way to handle that.  For example, use of a parser for the files through the help page.  Also, so far, all of the connectivity attempted here is via the server, not the client so what's valid for the server may not be valid for the client and visa versa.

2022-06-26 13:41 UTC, TheWitness commented
Good points mark.  You know what's really embarrassing is that I never gave consideration that the actual page accessing was going to take place client side.  The assumption that if the server can not get the page, the user can not is kind of silly.  But people, including I make false assumptions all the time.  It's human nature.  Maybe the way to do is this.

1) Client knows the page, and the status of local only.
2) If local only is not set, the client attempts to access the page via callback.
3) Check the status code, if invalid, then do a second callback to either get the message, or the local page.

Outside of the wording changes, this does not seem too dramatic.

2022-06-26 13:43 UTC, TheWitness commented on help.php
> +					'message' => __('The Document page \'%s\' count not be reached locally.  If you have installed from GitHub directly, consider downloading the distribution release and extracting the \'docs\' fol
Server argument agreed to.  How to automatically reconcile the "fetch it from XXX and install" I want to table for the moment.  If we host the HTML pages somewhere, we could for example, have a utility that pulls them separately, or even better, attempts to do so during the install process.  I would be okay deferring that for a subsequent change though.

2022-06-26 13:44 UTC, TheWitness commented on help.php
> +			} elseif ($contents != '' && preg_match('/does not appear to exist/i', $contents)) {
Yea, this is due to the documentation page never failing with a 404.  It always responds and then says the page does not exist.

2022-06-26 13:45 UTC, TheWitness commented on help.php
> +			if ($contents != '' && !preg_match('/does not appear to exist/i', $contents)) {
No, it always returns a 200 regardless if the page exists or not.

2022-06-26 13:45 UTC, TheWitness commented on help.php
> +			)
Yea, I agree with that.  It was a raw copy and past for some of our other context options setups.

2022-06-26 14:00 UTC, TheWitness commented
Well, this is lovely.  Can not access through a callback in that the server has a policy that forbids accessing it through a callback.

![image](https://user-images.githubusercontent.com/1439914/175817789-5c183861-bca5-4f1d-9e23-9f26f415667a.png)

2022-06-26 14:01 UTC, TheWitness commented
We should be able to relax that on the docs site don't you think?

2022-06-26 14:05 UTC, TheWitness commented
Here is the revised message now that I fixed the URL.

![image](https://user-images.githubusercontent.com/1439914/175818032-78d8be33-ff13-4466-bcc9-0e5ed74709d9.png)

2022-06-26 14:26 UTC, TheWitness commented
The client side is going to be an issue with fall back as unless we change the security policy on docs.cacti.net to

```
Access-Control-Allow-Origin: *
```

Otherwise, there is no way to auto-detect the pages existence through a callback.  It does not seem such a radical change to me as it's essentially a public static site.

2022-06-26 15:09 UTC, TheWitness commented
I went ahead and opened permissions a bit on the site.

2022-06-26 15:37 UTC, TheWitness commented on help.php
> +					'message' => __('The Document page \'%s\' count not be reached locally.  If you have installed from GitHub directly, consider downloading the distribution release and extracting the \'docs\' fol
This is all being handled now.  I had to allow Ajax calls on the docs site, but now it's working.

2022-06-26 15:38 UTC, TheWitness commented on help.php
> +						'message' => __('The Document page \'%s\' count not be reached.  The Cacti Documentation site is not reachable.  Consider downloading an official release to obtain the latest page help document
Message updated.  Still left directions, but message is now truncated.

2022-06-26 15:38 UTC, TheWitness commented on help.php
> +			)
Done.

2022-06-26 15:39 UTC, TheWitness commented
Everything updated now.  Please check the various error messages @Linegod

2022-06-26 16:32 UTC, TheWitness commented
`Where the first parameter is the page and the second is the URL to it. I am wondering if help pages should have their own array so we can use constants in the source.`

We have an array, but it's in the get_help_page() function.  It might be interesting to make it an CONSTANT array, but I think that support starts in PHP7.

2022-06-30 00:47 UTC, merged