QA: Add additional security to the unserialize function
Cacti/cacti pull request #5245
Opened 2023-02-20 13:44 UTC by TheWitness

* This change will add additional security to prevent certain classes of exploits in Cacti's use of the unserialize() function.
* Additionally, adding an additional setting to dsv_log() to reduce the amount of logging during use of the tool to test data sources vs. poller operations.

2023-02-22 17:26 UTC, netniV requested changes

2023-02-22 17:26 UTC, netniV commented on managers.php
> +			$selected_items = unserialize(stripslashes(get_nfilter_request_var('selected_items')), array('allowed_classes' => false));
Why does this not use the common unserialize_selected function?

2023-02-22 17:26 UTC, netniV commented on lib/html_form.php
> +			print "<option data-color='" . html_escape($color['hex']) . "' style='background-color: #" . html_escape($color['hex']) . ";' value='" . $color['id'] . "'";
Do we validate that hex is a hex on the way in?

2023-02-22 22:17 UTC, TheWitness commented on managers.php
> +			$selected_items = unserialize(stripslashes(get_nfilter_request_var('selected_items')), array('allowed_classes' => false));
It's returning an array and not a list of integers which the functions requires.  Why I thought we should move to json_encode() and maybe base64 encode that more long term.

2023-02-22 22:18 UTC, TheWitness commented on lib/html_form.php
> +			print "<option data-color='" . html_escape($color['hex']) . "' style='background-color: #" . html_escape($color['hex']) . ";' value='" . $color['id'] . "'";
Let me look into that.

2023-02-23 00:41 UTC, TheWitness commented on lib/html_form.php
> +			print "<option data-color='" . html_escape($color['hex']) . "' style='background-color: #" . html_escape($color['hex']) . ";' value='" . $color['id'] . "'";
Yea, it's validated, no need for the escape, but it's not a big deal as modified either.

2023-02-23 00:45 UTC, TheWitness commented on managers.php
> +			$selected_items = unserialize(stripslashes(get_nfilter_request_var('selected_items')), array('allowed_classes' => false));
So, being that the response is sensitive to not only the value but the index of the array values, I suggest we keep this as is for now.

2023-02-23 00:45 UTC, TheWitness commented on lib/html_form.php
> +			print "<option data-color='" . html_escape($color['hex']) . "' style='background-color: #" . html_escape($color['hex']) . ";' value='" . $color['id'] . "'";
So, I kept this as is.  The one change I did make was for the `dsv_log()`.  Good suggestion.

2023-02-24 03:44 UTC, netniV approved these changes

2023-02-24 03:45 UTC, merged