settings - column name extension
Cacti/cacti pull request #5442
Opened 2023-08-11 12:05 UTC by xmacan

Discusion:

Edit settings_user similarly?

value 75 hardcoded or add somewhere to include/files?

2023-08-11 12:31 UTC, netniV requested changes

2023-08-11 12:31 UTC, netniV commented on lib/functions.php
> +		cacti_log("WARNING: Config option name '$config_name' is too long, will be truncated", false, 'SYSTEM');
This should be an error not a warning. It creates a problem that can't be fixed by the end user.

2023-08-11 12:32 UTC, netniV approved these changes

2023-08-11 12:34 UTC, merged

2023-08-11 12:37 UTC, netniV commented
Yes settings_user should also be extended to match to avoid issues.

2023-08-11 12:38 UTC, xmacan commented
ok, I will do it

2023-08-12 01:29 UTC, TheWitness commented
Update the audit schema in the docs folder.

2023-08-28 09:58 UTC, netniV commented
Was the schema updated?

2023-08-28 09:59 UTC, xmacan commented
My bad, I will fix it

2023-08-28 11:13 UTC, TheWitness commented
I fixed it a few days ago.

2023-08-28 11:14 UTC, TheWitness commented
Last weekend during my QA testing.