Feat 5389 - When a new account is created or admin har reset password send email to user
Cacti/cacti pull request #5956
Opened 2024-12-04 14:47 UTC by xmacan

done #5389 

Adding log message too

2024-12-08 13:08 UTC, xmacan commented
@TheWitness - It is done, please check

2024-12-08 13:22 UTC, TheWitness commented
Will do.

2024-12-08 14:02 UTC, TheWitness requested changes

2024-12-08 14:02 UTC, TheWitness commented on include/global_settings.php
> +	'secnotify_resetlink_timeout' => array(
This setting is normally not more than say 15 minutes.  So, I would have:

5 Minutes
10 Minutes
15 Minutes
20 Minutes.

2024-12-09 13:54 UTC, TheWitness commented
@xmacan, did you see my request for change?

2024-12-09 15:03 UTC, xmacan commented
yes, I will do it asap

2024-12-09 15:29 UTC, xmacan commented on include/global_settings.php
> +	'secnotify_resetlink_timeout' => array(
done

2024-12-09 17:16 UTC, TheWitness approved these changes

2024-12-09 18:18 UTC, merged